using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;

namespace AOEOGearBasicLibrary.Helpers;
public static class UnitGearLookup
{
    private static readonly Dictionary<string, HashSet<string>> _civTraits = [];

    private static readonly Dictionary<string, BasicList<string>> _unitTraits = new(StringComparer.Ordinal)
    {
        ["Ba_Civ_Villager"] = ["Tools", "ArmorCloth", "GearVill"],
        ["Ba_Civ_FishingBoat"] = ["FishingNet", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ba_Civ_Caravan"] = ["Merchant", "ArmorCloth", "GearVill"],
        ["Ba_Civ_UtilityBoat"] = ["Merchant", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ba_Civ_OxCart"] = ["ArmorCloth", "GearVill"],
        ["Ba_Inf_Spearman"] = ["Spears2H", "ArmorMed", "Gear"],
        ["Ba_Inf_RoyalGuard"] = ["Swords1H", "Shields", "ArmorMed", "Gear"],
        ["Ba_Arc_Bowman"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["Ba_Cav_Scout"] = ["Swords1H", "ArmorLgt", "ScoutSpecial1H"],
        ["Ba_Cav_Lancer"] = ["Spears2H", "ArmorLgt", "Gear"],
        ["Ba_Sie_Palintonon"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["Ba_Spc_Priest"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Ba_Bldg_TownCenter"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_LookoutTower"] = ["ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_GuardTower"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_Fortress"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ba_Arc_Slinger"] = ["Sling", "ArmorCloth", "Gear"],
        ["Ba_Arc_ChariotArcher"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["Ba_Inf_Sapper"] = ["RamHeads", "ArmorMed", "Gear"],
        ["Ba_Arc_WarChariot"] = ["Javalins", "Shields", "ArmorLgt", "Gear"],
        ["Ba_Arc_MountedArcher"] = ["Bows", "Arrows", "ArmorLgt", "Gear"],
        ["Ba_Shp_Bireme"] = ["Bows", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ba_Shp_RamShip"] = ["RamHeads", "ArmorPlt", "GearBoat"],
        ["Ba_Inf_ShieldBearer"] = ["Spears1H", "Shields", "ArmorCloth", "Gear"],
        ["Ba_Bldg_Farm"] = ["ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_Market"] = ["ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_Armory"] = ["ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_ArcheryRange"] = ["ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_Stables"] = ["ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_Wonder"] = ["ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_Garden"] = ["ArmorBuilding", "GearBldg"],
        ["Ba_Bldg_SiegeWorkshop"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Inf_Spearman"] = ["Spears2H", "ArmorCloth", "Gear", "Warpaint"],
        ["Ce_Inf_LongSwordsman"] = ["Swords1H", "Shields", "ArmorCloth", "Gear", "Warpaint"],
        ["Ce_Inf_WoadRaider"] = ["GreatAxe", "War Horn", "Warpaint"],
        ["Ce_Inf_Champion"] = ["Swords1H", "ArmorMed", "Gear", "Warpaint"],
        ["Ce_Arc_Slinger"] = ["Sling", "Torc", "Gear"],
        ["Ce_Arc_Bowman"] = ["Bows", "Arrows", "Torc", "Gear"],
        ["Ce_Cav_Scout"] = ["Swords1H", "ArmorLgt", "ScoutSpecial1H"],
        ["Ce_Cav_Horseman"] = ["Spears2H", "ArmorLgt", "Gear"],
        ["Ce_Shp_Warship"] = ["Bows", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ce_Spc_Druid"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Ce_Spc_DruidAugur"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Ce_Civ_Villager"] = ["Tools", "ArmorCloth", "GearVill"],
        ["Ce_Civ_FishingBoat"] = ["FishingNet", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ce_Civ_UtilityBoat"] = ["Merchant", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ce_Civ_Caravan"] = ["Merchant", "ArmorCloth", "GearVill"],
        ["Ce_Bldg_TownCenter"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_LookoutTower"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_House"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_Farm"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_Market"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_GuardTower"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_Armory"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_ArcheryRange"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_Stables"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_SacredGrove"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_Fortress"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ce_Sie_Ram"] = ["RamHeads", "ArmorMed", "GearSiege"],
        ["Ce_Bldg_Wonder"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Bldg_GoldMine"] = ["ArmorBuilding", "GearBldg"],
        ["Ce_Arc_Carpentom"] = ["Javalins", "Shields", "ArmorCloth", "Gear"],
        ["Ce_Sie_Palintonon"] = ["BallistaArms", "ArmorMed", "GearSiege"],
        ["Eg_Bldg_Temple1"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Spc_PriestRa"] = ["Scepter", "ArmorCloth", "GearPriest"],
        ["Eg_Bldg_Temple2"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_Temple3"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Spc_PriestPtah"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Eg_Spc_PriestSet"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Eg_Arc_ChariotArcher"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["Eg_Arc_ElephantArcher"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["Eg_Arc_Slinger"] = ["Sling", "ArmorCloth", "Gear"],
        ["Eg_Bldg_Armory"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_Barracks"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_Dock"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_Farm"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_Fortress"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_GuardTower"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_Market"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_SiegeWorkshop"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_Stables"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_TownCenter"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_Wonder"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Bldg_StoreHouse"] = ["ArmorBuilding", "GearBldg"],
        ["Eg_Cav_Scout"] = ["Javalins", "ArmorLgt", "ScoutSpecial1H"],
        ["Eg_Cav_CamelRider"] = ["Spears2H", "ArmorLgt", "Gear"],
        ["Eg_Cav_WarElephant"] = ["Spears1H", "Shields", "ArmorLgt", "Gear"],
        ["Eg_Civ_Caravan"] = ["Merchant", "ArmorCloth", "GearVill"],
        ["Eg_Civ_FishingBoat"] = ["FishingNet", "Arrows", "ArmorPlt", "GearBoat"],
        ["Eg_Civ_UtilityBoat"] = ["Merchant", "Arrows", "ArmorPlt", "GearBoat"],
        ["Eg_Civ_Villager"] = ["Tools", "ArmorCloth", "GearVill"],
        ["Eg_Inf_Axeman"] = ["GreatAxe", "ArmorMed", "Gear"],
        ["Eg_Inf_Spearman"] = ["Spears2H", "ArmorMed", "Gear"],
        ["Eg_Shp_CatTrireme"] = ["BallistaArms", "ArmorPlt", "GearBoat"],
        ["Eg_Shp_Trireme"] = ["Bows", "Arrows", "ArmorPlt", "GearBoat"],
        ["Eg_Shp_FireShip"] = ["FireThrowers", "ArmorPlt", "GearBoat"],
        ["Eg_Sie_SiegeTower"] = ["RamHeads", "ArmorPlt", "GearSiege"],
        ["Eg_Sie_Catapult"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["Eg_Sie_Trebuchet"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["Gr_Bldg_Farm"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_TownCenter"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Gr_Civ_Villager"] = ["Tools", "ArmorCloth", "GearVill"],
        ["Gr_Inf_Spearman"] = ["Spears2H", "ArmorMed", "Gear"],
        ["Gr_Inf_Hoplite"] = ["Spears1H", "Shields", "ArmorMed", "Gear"],
        ["Gr_Inf_Hypaspist"] = ["Swords1H", "Shields", "ArmorMed", "Gear"],
        ["Gr_Arc_Toxotai"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["Gr_Cav_Hippikon"] = ["Swords1H", "Shields", "ArmorLgt", "Gear"],
        ["Gr_Arc_Peltast"] = ["Javalins", "Shields", "ArmorCloth", "Gear"],
        ["Gr_Cav_Podromos"] = ["Spears2H", "ArmorLgt", "Gear"],
        ["Gr_Sie_Ballista"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["Gr_Sie_BatteringRam"] = ["RamHeads", "ArmorPlt", "GearSiege"],
        ["Gr_Bldg_Barracks"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_Academy"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_ArcheryRange"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_Dock"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_Market"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_SiegeWorkshop"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_StoreHouse"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_Temple"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_LookoutTower"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_GuardTower"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_Armory"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Bldg_Stables"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Civ_Caravan"] = ["Merchant", "ArmorCloth", "GearVill"],
        ["Gr_Civ_FishingBoat"] = ["FishingNet", "Arrows", "ArmorPlt", "GearBoat"],
        ["Gr_Civ_UtilityBoat"] = ["Merchant", "Arrows", "ArmorPlt", "GearBoat"],
        ["Gr_Spc_Priest"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Gr_Shp_Trireme"] = ["Bows", "Arrows", "ArmorPlt", "GearBoat"],
        ["Gr_Shp_CatTrireme"] = ["BallistaArms", "ArmorPlt", "GearBoat"],
        ["Gr_Bldg_Fortress"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Gr_Sie_Palintonon"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["Gr_Cav_Scout"] = ["Swords1H", "ArmorLgt", "ScoutSpecial1H"],
        ["Gr_Bldg_Wonder"] = ["ArmorBuilding", "GearBldg"],
        ["Gr_Cav_Sarissophoroi"] = ["Javalins", "Shields", "ArmorLgt", "Gear"],
        ["Gr_Arc_Gastrophes"] = ["BellyBows", "Arrows", "ArmorCloth", "Gear"],
        ["Gr_Shp_FireShip"] = ["FireThrowers", "ArmorPlt", "GearBoat"],
        ["In_Bldg_Farm"] = ["ArmorBuilding", "GearBldg"],
        ["In_Bldg_StoreHouse"] = ["ArmorBuilding", "GearBldg"],
        ["In_Bldg_Monastery"] = ["ArmorBuilding", "GearBldg"],
        ["In_Bldg_Market"] = ["ArmorBuilding", "GearBldg"],
        ["In_Bldg_Shrine"] = ["ArmorBuilding", "GearBldg"],
        ["In_Bldg_GuardTower"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["In_Bldg_Dock"] = ["ArmorBuilding", "GearBldg"],
        ["In_Bldg_LookoutTower"] = ["ArmorBuilding", "GearBldg"],
        ["In_Bldg_Wonder"] = ["ArmorBuilding", "GearBldg"],
        ["In_Civ_Villager"] = ["Tools", "ArmorCloth", "GearVill"],
        ["In_Civ_GathererElephant"] = ["Tools", "ArmorCloth", "GearVill"],
        ["In_Spc_Guru"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["In_Civ_Caravan"] = ["Merchant", "ArmorCloth", "GearVill"],
        ["In_Civ_FishingBoat"] = ["FishingNet", "Arrows", "ArmorPlt", "GearBoat"],
        ["In_Civ_UtilityBoat"] = ["Merchant", "Arrows", "ArmorPlt", "GearBoat"],
        ["In_Shp_Vimana"] = ["Bows", "Arrows", "ArmorPlt", "GearBoat"],
        ["In_Shp_FireShip"] = ["FireThrowers", "ArmorPlt", "GearBoat"],
        ["In_Inf_Spearman"] = ["Spears2H", "ArmorMed", "Gear"],
        ["In_Inf_GadaWarrior"] = ["Clubs2H", "ArmorMed", "Gear"],
        ["In_Arc_Bowman"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["In_Arc_Ranger"] = ["Javalins", "Shields", "ArmorCloth", "Gear"],
        ["In_Cav_Turanga"] = ["Spears2H", "ArmorLgt", "Gear"],
        ["In_Arc_BladeChariot"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["In_Cav_WarElephant"] = ["Spears1H", "Shields", "ArmorLgt", "Gear"],
        ["In_Arc_ElephantArcher"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["In_Cav_Juggernaut"] = ["Swords1H", "Shields", "ArmorLgt", "Gear"],
        ["In_Sie_Ram"] = ["RamHeads", "ArmorMed", "GearSiege"],
        ["In_Sie_Palintonon"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["In_Inf_Scout"] = ["Swords1H", "ArmorCloth", "ScoutSpecial1H"],
        ["In_Inf_Monkey1"] = ["Clubs2H", "Shields", "ArmorMed", "Gear"],
        ["In_Arc_Monkey2"] = ["FireThrowers", "ArmorCloth", "Gear"],
        ["No_Civ_Villager"] = ["Tools", "ArmorCloth", "GearVill"],
        ["No_Civ_FishingBoat"] = ["FishingNet", "Arrows", "ArmorPlt", "GearBoat"],
        ["No_Civ_Caravan"] = ["Merchant", "ArmorCloth", "GearVill"],
        ["No_Civ_UtilityBoat"] = ["Merchant", "Arrows", "ArmorPlt", "GearBoat"],
        ["No_Inf_Scout1"] = ["Swords1H", "ArmorCloth", "ScoutSpecial1H"],
        ["No_Inf_Scout2"] = ["Bows", "Arrows", "ArmorCloth", "ScoutSpecial1H"],
        ["No_Arc_Skirmisher"] = ["Javalins", "Shields", "ArmorCloth", "Gear"],
        ["No_Inf_Axeman"] = ["GreatAxe", "Shields", "ArmorMed", "Gear"],
        ["No_Inf_Berserker"] = ["GreatAxe", "ArmorCloth", "Gear"],
        ["No_Inf_Ulfhednar"] = ["Spears1H", "ArmorCloth", "Gear"],
        ["No_Inf_Chief"] = ["GreatAxe", "ArmorMed", "Gear"],
        ["No_Arc_Bowman"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["No_Cav_Raider"] = ["Swords1H", "Shields", "ArmorLgt", "Gear"],
        ["No_Cav_Horseman"] = ["Spears2H", "ArmorLgt", "Gear"],
        ["No_Sie_Ram"] = ["RamHeads", "ArmorMed", "GearSiege"],
        ["No_Sie_Palintonon"] = ["BallistaArms", "ArmorMed", "GearSiege"],
        ["No_Spc_Bard"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["No_Shp_Longship"] = ["Bows", "Arrows", "ArmorPlt", "GearBoat"],
        ["No_Shp_FireShip"] = ["FireThrowers", "ArmorPlt", "GearBoat"],
        ["No_Spc_Seer"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["No_Inf_ThrowingAxeman"] = ["GreatAxe", "ArmorCloth", "Gear"],
        ["No_Cav_WarDog"] = ["Spears2H", "ArmorCloth", "Gear"],
        ["No_Bldg_TownCenter"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["No_Bldg_LookoutTower"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_Market"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_GuardTower"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["No_Inf_Spearman"] = ["Spears2H", "ArmorCloth", "Gear"],
        ["No_Bldg_Farm"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_Barracks"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_Armory"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_ArcheryRange"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_Stables"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_GreatHall"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_Fortress"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["No_Bldg_Wonder"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_StoreHouse"] = ["ArmorBuilding", "GearBldg"],
        ["No_Bldg_House"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Inf_Sparabara"] = ["Spears1H", "Shields", "ArmorCloth", "Gear"],
        ["Pe_Inf_Spearman"] = ["Spears2H", "ArmorMed", "Gear"],
        ["Pe_Inf_Immortal"] = ["Swords1H", "Arrows", "ArmorMed", "Gear"],
        ["Pe_Arc_Bowman"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["Pe_Arc_Takabara"] = ["Javalins", "Shields", "ArmorCloth", "Gear"],
        ["Pe_Cav_Scout"] = ["Swords1H", "ArmorLgt", "ScoutSpecial1H"],
        ["Pe_Cav_Asabara"] = ["Swords1H", "Shields", "ArmorLgt", "Gear"],
        ["Pe_Arc_MountedArcher"] = ["Bows", "Arrows", "ArmorLgt", "Gear"],
        ["Pe_Cav_Cataphract"] = ["Spears2H", "ArmorLgt", "Gear"],
        ["Pe_Sie_BatteringRam"] = ["RamHeads", "ArmorPlt", "GearSiege"],
        ["Pe_Sie_WarWagon"] = ["Bows", "Arrows", "ArmorPlt", "GearSiege"],
        ["Pe_Sie_Palintonon"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["Pe_Shp_Galley"] = ["Bows", "Arrows", "ArmorPlt", "GearBoat"],
        ["Pe_Shp_RamShip"] = ["RamHeads", "ArmorPlt", "GearBoat"],
        ["Pe_Spc_Magus"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Pe_Civ_Villager"] = ["Tools", "ArmorCloth", "GearVill"],
        ["Pe_Civ_FishingBoat"] = ["FishingNet", "Arrows", "ArmorPlt", "GearBoat"],
        ["Pe_Civ_Caravan"] = ["Merchant", "ArmorCloth", "GearVill"],
        ["Pe_Civ_UtilityBoat"] = ["Merchant", "Arrows", "ArmorPlt", "GearBoat"],
        ["Pe_Shp_MangonelGalley"] = ["BallistaArms", "ArmorPlt", "GearBoat"],
        ["Pe_Bldg_WarAcademy"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_ArcheryRange"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_Armory"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_Barracks"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_Dock"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_Fortress"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_GuardTower"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_LookoutTower"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_Market"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_SiegeWorkshop"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_Stables"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_StoreHouse"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_TownCenter"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_Wonder"] = ["ArmorBuilding", "GearBldg"],
        ["Pe_Bldg_ImmortalCamp"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_House"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Fortress"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_TownCenter"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Barracks"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_AuxiliaCamp"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_OfficerTent"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_SiegeWorkshop"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Armory"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Farm"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_StoreHouse"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Forum"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Market"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Templum"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_GuardTower"] = ["Bows", "Arrows", "ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Dock"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_LookoutTower"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Bldg_Wonder"] = ["ArmorBuilding", "GearBldg"],
        ["Ro_Civ_Villager"] = ["Tools", "ArmorCloth", "GearVill"],
        ["Ro_Civ_Engineer"] = ["Tools", "ArmorCloth", "GearVill"],
        ["Ro_Spc_Clinicus"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Ro_Civ_Caravan"] = ["Merchant", "ArmorCloth", "GearVill"],
        ["Ro_Civ_FishingBoat"] = ["FishingNet", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ro_Civ_UtilityBoat"] = ["Merchant", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ro_Shp_Liburnian"] = ["Bows", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ro_Shp_Enneris"] = ["BallistaArms", "Arrows", "ArmorPlt", "GearBoat"],
        ["Ro_Inf_Spearman"] = ["Spears2H", "ArmorMed", "Gear"],
        ["Ro_Inf_Legionary"] = ["Swords1H", "Shields", "ArmorMed", "Gear"],
        ["Ro_Cav_Eques"] = ["Spears1H", "Shields", "ArmorLgt", "Gear"],
        ["Ro_Arc_Slinger"] = ["Sling", "ArmorCloth", "Gear"],
        ["Ro_Arc_Bowman"] = ["Bows", "Arrows", "ArmorCloth", "Gear"],
        ["Ro_Cav_Horseman"] = ["Spears2H", "ArmorLgt", "Gear", "Warpaint"],
        ["Ro_Inf_Aquilifer"] = ["Swords1H", "War Horn", "ArmorCloth", "Gear", "Banner"],
        ["Ro_Inf_Centurion"] = ["Swords1H", "Shields", "ArmorMed", "Gear", "Javalins"],
        ["Ro_Cav_Decurion"] = ["Swords1H", "Shields", "ArmorLgt", "Gear"],
        ["Ro_Cav_PrimusPilus"] = ["Swords1H", "Shields", "ArmorLgt", "Gear", "Banner"],
        ["Ro_Sie_BatteringRam"] = ["RamHeads", "ArmorPlt", "GearSiege"],
        ["Ro_Sie_Scorpio"] = ["BellyBows", "ArmorMed", "GearSiege"],
        ["Ro_Sie_Onager"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["Ro_Sie_Palintonon"] = ["BallistaArms", "ArmorPlt", "GearSiege"],
        ["Ro_Spc_Priest"] = ["Staffs2H", "ArmorCloth", "GearPriest"],
        ["Ro_Cav_Scout"] = ["Swords1H", "ArmorLgt", "ScoutSpecial1H"],
        ["Ro_Bldg_Millarium"] = ["ArmorBuilding", "GearBldg"]
    };
    private static HashSet<string>? _allGearCategories;

    public static BasicList<string> GetAllGearCategories()
    {
        if (_allGearCategories is null)
        {
            _allGearCategories = _unitTraits
                .SelectMany(x => x.Value)
                .ToHashSet(StringComparer.Ordinal);
        }
        return _allGearCategories.ToBasicList();
    }
    public static BasicList<string> GetTraitsForUnit(string unitName)
    {
        if (_unitTraits.TryGetValue(unitName, out BasicList<string>? traits))
        {
            return traits;
        }
        throw new CustomBasicException($"No gear for {unitName}");
    }


    public static HashSet<string> GetTraitTypesForCivilization(string civAbb)
    {
        if (_civTraits.TryGetValue(civAbb, out var traits) == false)
        {
            traits = _unitTraits
                .Where(x => x.Key.StartsWith(civAbb + "_", StringComparison.Ordinal))
                .SelectMany(x => x.Value)
                .ToHashSet(StringComparer.Ordinal);

            _civTraits[civAbb] = traits;
        }

        return traits;
    }

    public static bool CanCivilizationUseGear(string civAbb, string gearCategory)
    {
        if (_civTraits.TryGetValue(civAbb, out var traits) == false)
        {
            traits = _unitTraits
                .Where(x => x.Key.StartsWith(civAbb + "_", StringComparison.Ordinal))
                .SelectMany(x => x.Value)
                .ToHashSet(StringComparer.Ordinal);

            _civTraits[civAbb] = traits;
        }

        return traits.Contains(gearCategory);
    }
}